name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # Replace 'anuragn2107' with your exact HF username/space name format
        run: git push --force https://anuragn2107:$HF_TOKEN@huggingface.co/spaces/anuragn2107/Retainx-Churn-Prediction main
